{% set name = "ewmh" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ewmh-{{ version }}.tar.gz
  sha256: c56b093f7d575181e979bb3a7d15c34065755f811c351ff0a31fede12b09343d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - python-xlib

test:
  imports:
    - ewmh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/parkouss/pyewmh
  summary: python implementation of Extended Window Manager Hints, based on Xlib
  doc_url: https://pythonhosted.org/ewmh/
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - '0xbe7a'
